baseURL = "https://podatekodkrypto.pl"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Podatek od krypto"
[markup.goldmark.renderer]
unsafe = true
