############################# English ############################
[en]
languageName = "En"
title = "Podatek od krypto"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = ""
footer_menu_middle = "Usługi"
footer_menu_right = "Linki"
footer_content = ""
# copyright
copyright = "Wszystkie prawa zastrzeżone"