footer_middle = []
[[footer_left]]
name = ""
url = ""
[[footer_right]]
name = "Aktualności"
url = "https://podatekodkrypto.pl/aktualnosci/"
[[footer_right]]
name = "Kontakt"
url = "https://podatekodkrypto.pl/kontakt/"
[[main]]
name = "Aktualności"
url = "aktualnosci"
weight = 1
[[main]]
name = "Cennik"
url = "cennik"
weight = 2
[[main]]
name = "Kontakt"
url = "kontakt"
weight = 3
