footer_middle = []
[[footer_left]]
name = ""
url = ""
[[footer_right]]
name = "Aktualności"
url = "https://podatekodkrypto.pl/blog/"
[[footer_right]]
name = "Kontakt"
url = "https://podatekodkrypto.pl/contact/"
[[main]]
name = "Aktualności"
url = "blog"
weight = 1
[[main]]
name = "Cennik"
url = "pricing"
weight = 2
[[main]]
name = "Kontakt"
url = "contact"
weight = 3
