author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
logo = "images/logo.png"
logo_width = "200px"
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[plugins.css]]
link = "plugins/slick/slick.css"
[[plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[plugins.js]]
link = "plugins/slick/slick.min.js"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "ti-facebook"
link = "https://www.facebook.com/groups/podatekodkrypto/"
title = "facebook"
