# Bigspring Hugo Startup Theme
# https://gethugothemes.com
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.
contact_form_action = "https://formspree.io/f/mgerwnvl" # contact form works with https://formspree.io